name: CI

on:
  push:
    branches:
      - gh-page

env:
  GIT_USER: hsipeng
  GIT_EMAIL: hsi.peng@outlook.com
  DEPLOY_REPO: hsipeng/hsipeng.github.io
  DEPLOY_BRANCH: gh-page

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install yarn
        run: |
          npm install -g yarn
      - name: Install dependencies
        run: |
          yarn install
      - name: Build html
        run: |
          npm run build
      - name: add stage
        run: |
          git add .
      - name: commit
        run: |
          git commit -am "update by github action"
      - name: push to github
        run: |
          git push
